name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYLINT_SCRIPT: scripts/pylint.sh

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Analysing the code with pylint
        run: |
          chmod +x ${{ env.PYLINT_SCRIPT }}
          ./${{ env.PYLINT_SCRIPT }}
